cc_test(
    name = "tests",
    srcs = glob(["*.cc"]),
    deps = [
        "//src/collections:skiplist",
        "//src/collections:vector",
        "//src/math:number-theory",
        "@googletest//:gtest_main",
    ],
)
