cc_test(
    name = "tests",
    srcs = glob(["*.cc"]),
    deps = [
        "//src/collections:vector",
        "//src/iterator:iterator",
        "//src/math:number-theory",
        "@googletest//:gtest_main",
        ],
    )
