cc_library(
    name = "vector",
    hdrs = ["vector.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "linked-list",
    hdrs = ["linked-list.h"],
    visibility = ["//visibility:public"],
)
