cc_library(
    name = "vector",
    hdrs = ["vector.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "skiplist",
    hdrs = ["skiplist.h"],
    visibility = ["//visibility:public"],
)
